//! Byte-identity vectors for every wire encoding of the key and signature types, across all
//! 17 algorithms.
//!
//! The expected values were generated by pqc-sig **0.4.2**, before the signature backends
//! became optional features in 0.5.0, using `print_encoding_vectors` below on the 0.4.2
//! tree. This file runs in every feature combination, including
//! `--no-default-features --features std` where no signature implementation is compiled,
//! so it proves the encoding-only build produces exactly the bytes the full crate always
//! has.
//!
//! Each entry is the SHA-256 of the encoded string rather than the string itself, because
//! SLH-DSA signatures run to ~66 KB of base64url. The multibase strings are also committed
//! in full in `multibase_tests.rs`.
//!
//! **Never regenerate these to make a test pass.** A changed value is a changed wire
//! format, which is a breaking change under `STABILITY.md`.

use pqc_sig::types::{SigAlgorithm, SigPublicKey, Signature, SignedMessage};
use sha2::{Digest, Sha256};

const ALL: [SigAlgorithm; 17] = [
    SigAlgorithm::MlDsa44,
    SigAlgorithm::MlDsa65,
    SigAlgorithm::MlDsa87,
    SigAlgorithm::SlhDsaSha2_128s,
    SigAlgorithm::SlhDsaSha2_128f,
    SigAlgorithm::SlhDsaSha2_192s,
    SigAlgorithm::SlhDsaSha2_192f,
    SigAlgorithm::SlhDsaSha2_256s,
    SigAlgorithm::SlhDsaSha2_256f,
    SigAlgorithm::SlhDsaShake128s,
    SigAlgorithm::SlhDsaShake128f,
    SigAlgorithm::SlhDsaShake192s,
    SigAlgorithm::SlhDsaShake192f,
    SigAlgorithm::SlhDsaShake256s,
    SigAlgorithm::SlhDsaShake256f,
    SigAlgorithm::FnDsa512,
    SigAlgorithm::FnDsa1024,
];

/// Deterministic, non-random bytes: byte `i` has value `(i * 7 + seed) % 256`.
fn bytes(len: usize, seed: u8) -> Vec<u8> {
    (0..len).map(|i| ((i * 7 + seed as usize) % 256) as u8).collect()
}

fn public_key(algo: SigAlgorithm) -> SigPublicKey {
    SigPublicKey::new(algo, bytes(algo.public_key_size(), 1))
}

fn signature(algo: SigAlgorithm) -> Signature {
    Signature::new(algo, bytes(algo.signature_size(), 2))
}

const MESSAGE: &[u8] = b"pqc-sig encoding vector";

fn sha256_hex(s: &str) -> String {
    Sha256::digest(s.as_bytes()).iter().map(|b| format!("{b:02x}")).collect()
}

/// The five encodings of one algorithm, in a fixed order.
fn encodings(algo: SigAlgorithm) -> [String; 5] {
    let pk = public_key(algo);
    let sig = signature(algo);
    [
        pk.to_multibase().expect("multibase"),
        pk.to_json().expect("public key json"),
        sig.to_base64url(),
        sig.to_json().expect("signature json"),
        SignedMessage::new(MESSAGE.to_vec(), sig.clone(), pk.clone())
            .to_json()
            .expect("signed message json"),
    ]
}

const NAMES: [&str; 5] = [
    "public key multibase",
    "public key json",
    "signature base64url",
    "signature json",
    "signed message json",
];

/// (algorithm, SHA-256 of each encoding in `NAMES` order), generated by pqc-sig 0.4.2.
const VECTORS: &[(SigAlgorithm, [&str; 5])] = &[
    (SigAlgorithm::MlDsa44, [
        "c3d950e9f675d3ce55bdc2d09a86491e7b54492c51eb2fceaa5b44048e82a403",
        "c00f72e40c5a9a33047e517ffc2a1b63ee14b326adc79d2c1bd5d897dc0aad3b",
        "fa2d5b0ef9b02c457d9b9fd803542e35c9f91601910464d60fc06da80ffe04fc",
        "5f9b9c15a9b5caa258b9818b9b0bca319b813d684b2d75cf25bec0544e4c2915",
        "3e5f4b79904ecab5076f3e4d126584870c4a45909103e088d0389ee9deee0274",
    ]),
    (SigAlgorithm::MlDsa65, [
        "26003572dd74d765f69a65d9d4b7a3c130af4157941af8bdca9076d77372531c",
        "655560be4939945a2fcd2d0011fb3e0bfbe95ceaf26a49bc6eafbc9b8e2be71d",
        "2cf1effedb3fab39e6bdf8aa22a44bb4b07d1d286cdbd25d0303778bad74e9f3",
        "13e84cb9b552226077c40fa01093f5156a45d969a349ea056896ba673486ac5f",
        "3b92d3fe6851a334c1bd22cec22ee252a466c6892f3cc0b0bca80ec576bba09c",
    ]),
    (SigAlgorithm::MlDsa87, [
        "3ad7db46df776ff8589103eb9ae96d589925f3006ddd90124d98fd2a80fc0d73",
        "28e7497554ab236e857346e26449f1004416edf7330deaeea17a3b647edfe453",
        "331e16443351997a12133eefc0f617dbd7448d887092b9535f547a4dc82ee818",
        "9e1763913bc90ce104209b2d61e3bf472adacbe0425e372110f75a5cf9196679",
        "90e2f491cf288fe4bbe0faa641ba945b23bced6af5db75a9e01c7ac651925c71",
    ]),
    (SigAlgorithm::SlhDsaSha2_128s, [
        "bdaf838f23a311893262b8e085234324736d8763402fdc381248288440de76a6",
        "7b9b6339bf60586f4b56aa03a7c6ae39699eb9e0b1d3b054f00993da63a24781",
        "0c948a261b44268d2bde8b5e11b6215d3623356d81aa4d7a388817e629d6c09a",
        "7d7e6e7c731b5ff2ae3ce42168063951f61a9b562549dfdc272c9d5bfeb68bf5",
        "76cafb80d588aa2fd36063333141be6364605bebdef3803dbce1347e33533d8b",
    ]),
    (SigAlgorithm::SlhDsaSha2_128f, [
        "d613bc4b5fc602d759a0cc2f3a154f413c9f2cd88a6763cf03cd9b4e222350f9",
        "6d5db21de43d2563d9e83f5d4a2ac533f6a378360590f62ca00f90373b1b43be",
        "e9cc2e6c64bf3ae986f4dff3e77aa28e5fc82881cfd30390595a81452af91c25",
        "6925e2af30fa0c086da97c281183f6cc2796e96fb467066d591f2c7bc130dcaa",
        "32d19d13f55b5fe4ae2fbdbf5c221398083669fb5279eccb63360f362ef1b7fa",
    ]),
    (SigAlgorithm::SlhDsaSha2_192s, [
        "dc530fd07ebda41123a3a0c02cc3812b443a3e7c9222a191ec20a0b63a6e5769",
        "a8868198f1badc56e68530f2a1bbfd01222a206a3a447162b2e4484a8014abde",
        "7a8ea349d0b7874f4c01a31559c7549e5c5804b4da1f3260496ed6d525c52e0d",
        "93c60ffcc347aead66b9e93570a62be8bfdb944e84ce6ba9aa993a3693cf40cd",
        "51f3a58f2a85d76265787cfa1dd72603e06f21cf48881e4010795bc0b0751743",
    ]),
    (SigAlgorithm::SlhDsaSha2_192f, [
        "2f3fa8b8e134e7fa0ea0dfc49016563ce6a8f338791cd237495750ebb4e13166",
        "7646fb9c05ad75a0aa1b08dcd9bb90d955f11748cf3b91fe1d5528efd70a381a",
        "3b42c7b7e9618d376f4cf5d9b8e52b4c53a5c9602ec8950bffc0e430168414b4",
        "08b3f2a6dcf76ea66348f7497708cf098390d3c9f623773537b1861eb24718e2",
        "424eec2c87c4ae0fb0b7bd30a16e971d9566d6d51797a6c6d4b726c7e457159a",
    ]),
    (SigAlgorithm::SlhDsaSha2_256s, [
        "84e8eee176145df4fd195b2dd56715f130626e22fa2c8ba882d9c5aa995b4e51",
        "f5601a6b7877b50518bb12b298f03a2ab2767fc45a77c259cfd8634efe5ec514",
        "5cc7a17ab736257707f640a36da3bd75f6d7b7d2dbb4ccad288d935e197cbbd6",
        "773d998baaaf1f6d5a2412e7950b570200b98c4d551bca178e504b2d9039abc9",
        "373dd8447338e386fa8ea5f6510f0c38d9249448c9e34e8f321cd2a4a84e1f57",
    ]),
    (SigAlgorithm::SlhDsaSha2_256f, [
        "9df5c1a157ff54f0d1a4691cf1522b23e27e76717865258fdcf7734febd60926",
        "9e9558f6f16ffb6293905dea577d02273f38712794f337ef33c82c9166406098",
        "dd1a76b64ffaad39df9fdcf983c8630a30c1d42a3227e2ab5ef5c65facbf7eb1",
        "5f02c97280f5456f72f2abc9117dd138202f828d140189e09322094698968271",
        "ec15ceb240e9001dd159d274e0420514cc748543de44a7a081972c3c2b9da0a0",
    ]),
    (SigAlgorithm::SlhDsaShake128s, [
        "162c742a9302b37396711a51f77f37f2014e6aea3a1dda8d4b0339fbd76a9edc",
        "06797f31b6755d02eb15bff778a269927dc3434a4d3dc747c1c41334d6499fab",
        "0c948a261b44268d2bde8b5e11b6215d3623356d81aa4d7a388817e629d6c09a",
        "1bdf39b459a77b2553a1170e422f9ba29e8adf8879728fa5c2e728427b95949d",
        "78a269a3e6535ccaedf6adfcbb340832c1bebf904c5bd8c12281839496ce4397",
    ]),
    (SigAlgorithm::SlhDsaShake128f, [
        "b5d2407348a44f2f3e251dc4664abc9fa9a79ef532f7b8a26aabcf0cfee90e09",
        "16ceffc17686b704a95491236857962393d909d6159ed56ea8650910a5943399",
        "e9cc2e6c64bf3ae986f4dff3e77aa28e5fc82881cfd30390595a81452af91c25",
        "fee39a704480760a0e6535f421cc9f99afe096bb16cd1a0c8619b4a4bfbc7138",
        "13d5d3dc7ddc19e685b51376c7bd3eb12a358771b3491e769314224bc073b039",
    ]),
    (SigAlgorithm::SlhDsaShake192s, [
        "fb64c078d11e6166f32a7bb3cf59892128d69349ee405807aacb8a530c6b4c1e",
        "d0433397ca81e155718b869a470653da28be4031528f0b15b48410956d60ccab",
        "7a8ea349d0b7874f4c01a31559c7549e5c5804b4da1f3260496ed6d525c52e0d",
        "dbbba5454d4b9338900f6b731c0e9c35ee18e7d8e136caec0ce2e61a66da8279",
        "9a40e2ef6df444ff08b103e3db54a13c7f087b541750e3498dfce5b4bc80a9a5",
    ]),
    (SigAlgorithm::SlhDsaShake192f, [
        "5621b029f2f36ef7b3b7e23e6678bfd86da508bca2ae73518bcd942e6eca6e50",
        "c9a0f6fbad33a25877354e119f7bffb0b0b934cc02a2ea23558857747b767054",
        "3b42c7b7e9618d376f4cf5d9b8e52b4c53a5c9602ec8950bffc0e430168414b4",
        "76fcc82028c6d050d4878fb0f630f2379e34beedabc690cc705664163de8ceb5",
        "3b47a1cf45cb993f6873b272052a563478321a1bf2b3f54c7f54083d794a9b62",
    ]),
    (SigAlgorithm::SlhDsaShake256s, [
        "3b8cd884a8bce1719fc54f22bbbb9bb549134d2e0b75bfa020f97198c5432dba",
        "a71d58e2211fb5afba457441b7c8d350bef05d954ccc6dee2a46ff8c09b32263",
        "5cc7a17ab736257707f640a36da3bd75f6d7b7d2dbb4ccad288d935e197cbbd6",
        "938dd71dc818494b0bfa43772cc21f0f3a16e344dae6adfb8c87f687ab795008",
        "81cfdc9bc1c27db80f448180aa26dcea6edf563fb077e96cf560a1eb821b9e6e",
    ]),
    (SigAlgorithm::SlhDsaShake256f, [
        "83be8fba85d77915b49fc64565c42a9cb753b8d2d05a4fc97661aa270df97bbd",
        "5f4a868a57b20cb52fac0494698f844ec9d097a7d78788f48de661d0a9e3c80e",
        "dd1a76b64ffaad39df9fdcf983c8630a30c1d42a3227e2ab5ef5c65facbf7eb1",
        "cb5fa5a479b10d58af6fcdd704b876f5b97143d8adfc78bee641b2a5b14b323d",
        "20306a6957ab447903cc4cd668731f499caa60de8a48b0d68dc39290d186a6c0",
    ]),
    (SigAlgorithm::FnDsa512, [
        "2d677b20dfb32c42f48d39ea9ccb030b17481d844f0ec2e812a7bffdf1ca6c07",
        "4451c7b668aa8350fab3c91bf05963d13e7feb2ad13a095f950b89aa3455ca46",
        "b379797b9281bedef42acd2154315c8a0dfc2aec566aabc8c26d6027c46f894d",
        "d14296919d73c78248fe43e893dc4dbac21d05e746b16df8d18e90ee8f31ca4f",
        "aec3e8e0ab538941470db61a258fc95a6ee04ae44bfd4e3a1e0f3bfcc9d7d6d3",
    ]),
    (SigAlgorithm::FnDsa1024, [
        "00311b48fb1c8005faa20c062f1e63f0d419bd6f077426534f937eba7812ec36",
        "27e43fc704476dfd4d76cc1ea59572a619ea37a991fd2616e50ff2f9d08af794",
        "f759963ef800ffe529fcdf06b6a38d19e48e2821828e6b9b419098e5168862b8",
        "5af36a4088c78579018ffcd9f4b1ba390dd9f5ea1d794e8d695bc5bd24fac0a0",
        "47ae0980e5f19ef853d61a0bdf348832fa2c269f52acb6ecf681d2e3ee9a888c",
    ]),
];

#[test]
fn every_algorithm_has_a_vector() {
    assert_eq!(VECTORS.len(), ALL.len(), "one vector per algorithm");
    for (algo, (vector_algo, _)) in ALL.iter().zip(VECTORS) {
        assert_eq!(algo, vector_algo);
    }
}

#[test]
fn encodings_match_the_0_4_2_output() {
    for (algo, expected) in VECTORS {
        for ((name, encoded), want) in NAMES.iter().zip(encodings(*algo)).zip(expected) {
            assert_eq!(&sha256_hex(&encoded), want, "{algo:?} {name}");
        }
    }
}

/// The check can fail: changing one byte of the input changes every digest.
#[test]
fn a_one_byte_change_is_detected() {
    let algo = SigAlgorithm::MlDsa65;
    let mut pk = public_key(algo);
    pk.bytes[0] ^= 1;
    assert_ne!(sha256_hex(&pk.to_multibase().unwrap()), VECTORS[1].1[0]);
    let mut sig = signature(algo);
    sig.bytes[0] ^= 1;
    assert_ne!(sha256_hex(&sig.to_base64url()), VECTORS[1].1[2]);
}

#[test]
fn encodings_decode_to_the_original_values() {
    for algo in ALL {
        let pk = public_key(algo);
        let sig = signature(algo);
        let [multibase, pk_json, sig_b64, sig_json, msg_json] = encodings(algo);

        assert_eq!(SigPublicKey::from_multibase(algo, &multibase).unwrap(), pk, "{algo:?}");
        assert_eq!(SigPublicKey::from_json(&pk_json).unwrap(), pk, "{algo:?}");
        assert_eq!(Signature::from_base64url(algo, &sig_b64).unwrap(), sig, "{algo:?}");
        assert_eq!(Signature::from_json(&sig_json).unwrap(), sig, "{algo:?}");

        let msg = SignedMessage::from_json(&msg_json).unwrap();
        assert_eq!(msg.message, MESSAGE, "{algo:?}");
        assert_eq!(msg.signature, sig, "{algo:?}");
        assert_eq!(msg.public_key, pk, "{algo:?}");
    }
}

/// Prints the `VECTORS` table. Run on the tree whose output is the reference:
/// `cargo test --test encoding_vectors -- --ignored --nocapture print_encoding_vectors`
#[test]
#[ignore = "generator, not a check"]
fn print_encoding_vectors() {
    for algo in ALL {
        let digests: Vec<String> =
            encodings(algo).iter().map(|e| format!("\"{}\"", sha256_hex(e))).collect();
        println!("    (SigAlgorithm::{algo:?}, [\n        {},\n    ]),", digests.join(",\n        "));
    }
}
